-- Catalog module schema. See docs/adr/0004-relational-postgres-system-of-record.md.
create table product (
    id     bigint generated by default as identity primary key,
    name   varchar(255)   not null,
    price  numeric(12, 2) not null,
    active boolean        not null
);
